### ISSUE TITLE
HieWrapper discovers the wrong ghc version in a multi-stack cradle

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-ide-engine#1490]
In a project, with a hie.yaml such as
````yaml
cradle:
  stack:
    - path: .
      component: "package:lib"
````
Hie will identify this as a "Multi-Cradle". 
A hie.yaml such as:
````yaml
cradle:
  cabal:
    - path: .
      component: "lib:package"
````
Will also be identified as a "Multi-Cradle".

Haskell IDE Engine can not tell the difference between a `"Cabal"-Multi-Cradle` and a `"Stack"-Multi-Cradle`, but it should.

Moreover, I suggest that the following should be handled gracefully:

```yaml
cradle:
  multi:
    - path: .
      config:
        cradle:
          cabal: 
            component: "lib:package"
    - path: examples/
      config:
        cradle:
          none:
```

I think, that this still should be identified as a `Cabal-Multi-Cradle` and analogously the `Stack-Multi-Cradle`.
Support for this feature needs to be implemented in `hie-bios`.

cc @mpickering 

Issue is encountered in #1482.
