### ISSUE TITLE
HIE gives "could not execute: <some preprocessor exe>"

### ISSUE THREAD

**Issue by Ailrun** [haskell/haskell-ide-engine#1500]
In stack cradle (more specifically, I use multi-cradle with stack), if a preprocessor executable is installed only locally but not globally, HIE says `could not execute: <the name of the preprocessor>`.
For my case, I use `tasty-discover`, and my `package.yaml` specify it as a dependency like this,
```yaml
tests:
  test:
    main: Driver.hs
    source-dirs:
      - test
    dependencies:
      - hedgehog
      - tasty
      - tasty-discover
      - tasty-hedgehog
```
but HIE emits `could not execute: tasty-discover`.

Maybe this is related to mpickering#60 and will be solved by #1496, but I am not sure.
