### ISSUE TITLE
HIE failing on test directory - multi cradle configuration.

### ISSUE THREAD

**Issue by drewboardman** [haskell/haskell-ide-engine#1613]
I'm running hie+ nix with the all-hies cachix binaries. The production code works fine, however the test files fail with the following:

```shell
2020-01-28T17:16:46.020 DEBUG (pid:157615) [language-client-index] - [languageserver.haskell] 2020-01-28 17:16:46.02033692 [ThreadId 15] - Fail on cradle initialisation: (ExitFailure 1)["Failed to parse result of calling cabal","Resolving dependencies...
Build profile: -w ghc-8.6.4 -O1
In order, the following will be built (use -v for more details):
- myPackage-0.1 (lib) (configuration changed)
- myPackage-0.1 (test:test) (first run)
Configuring library for myPackage-0.1..
Preprocessing library for myPackage-0.1..
Building library for myPackage-0.1..
","Warning: 'ghc-options: -threaded' has no effect for libraries. It should
only be used for executables.
Warning: 'ghc-options: -rtsopts' has no effect for libraries. It should only
be used for executables.
gcc: error:
/home/drew/code/myRepo/dist-newstyle/build/x86_64-linux/ghc-8.6.4/myPackage-0.1/build/myPackage/DB/Schema.dyn_o:
No such file or directory `cc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build myPackage-0.1 (which is required by test:test from myPackage-0.1).
",""]

2020-01-28T17:16:46.020 DEBUG (pid:157615) [language-client-index] - [languageserver.haskell] 
2020-01-28 17:16:46.020566651 [ThreadId 15] - ghcDispatcher:Got error for a request: IdeError 
{ideCode = OtherError, ideMessage = "Fail on initialisation for \"/home/drew/code/myRepo/test/src
/myPackage/Tests/DB/XX/Thing.hs\". Failed to parse result of calling cabal", ideInfo = Null} with mid: 
Nothing
```
My `hie.yaml` is:

```yaml
cradle:
  cabal:
    - path: "./exec/build"
      component: "exe:build"
    - path: "./"
      component: "lib:myproject"
    - path: "./exec/myproject"
      component: "exe:myproject"
    - path: "./test/src"
      component: "test:test"
```

The test portion of `package.yaml` is:

```yaml
tests:
  test:
    main: Main.hs
    source-dirs: test/src
    ghc-options:
      - -with-rtsopts=-N
      - -Wall
      - -Werror
```
