### ISSUE TITLE
How to reflect mixins?

### ISSUE THREAD

**Issue by koowashi** [haskell/haskell-ide-engine#1705]
# Environment
OS: Ubuntu 18.04.4 LTS (Bionic Beaver)
hie: Version 1.1, Git revision c584f98 (3811 commits) x86_64 ghc-8.6.5
stack: Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
IDE: VS Code

# Problem

HIE raise an error although `$ stack run` succeed.

# Detail

I created a new stack project.

put `hie.yaml` and HIE works fine at this point.

change dependencies of  `package.yaml`:

```yaml
dependencies:
- name: base
  mixin: hiding (Prelude)
- name: relude
  mixin: (Relude as Prelude)
```

my `Main.hs`:

```hs
module Main where

main :: IO ()
main = pass
```

`$ stack run` succeed.

(`Relude` is imported implicitly and it exports `pass`)

but I got HIE's error:

```
Variable not in scope: pass :: IO ()
```

How to reflect mixins?
