### ISSUE TITLE
coc, hie, ghci stack ... ghci cannot find the modules defined by the project

### ISSUE THREAD

**Issue by EdmundsEcho** [haskell/haskell-ide-engine#1711]
Hello - 

I moved from a prior config using ALE and others to the new `hie`.  I'm excited about what you all have accomplished.  I'm getting the following error:

```
Could not find module ‘DB.API’ Use -v (or `:set -v` in ghci) to see a list of the files searched for. |22 | import qualified DB.API as Lib
etc... for all of the modules defined in my project
```

Despite my best judgment, I have `hie` installed globally.  However, I have `package.yaml` and `hie.yaml` in my project root folder.  
```
cradle:
  stack:
    component: "haskell-ide-engine:lib"

dependencies:
  - package.yaml
```
Also, when I run `hie` from my root folder, it echoes/prints the project file names.

A. Am I "barking up the right tree" reaching out to the `hie` team?
B. If A, then what am I missing to get `ghci` to see my project modules?

Thank you in advance!

\- E

**Comment by fendor** [comment]
Yes, you have barked up the right tree :)
The `hie.yaml` looks like it has been copied from some other example.
It should reflect a map from filepaths to components. Components in haskell are things like `library`, `executable`, `test` or `benchmark`. 
For example, a simplified `hie.yaml` for HIE codebase:
```yaml
cradle:
  stack:
    - path: "./hie-plugin-api/"
      component: "hie-plugin-api:lib"

    - path: "./app/MainHie.hs"
      component: "haskell-ide-engine:exe:hie"

    - path: "./app/HieWrapper.hs"
      component: "haskell-ide-engine:exe:hie-wrapper"

    - path: "./"
      component: "haskell-ide-engine:lib"
```
Here we say, any FilePath that starts with `hie-plugin-api` should be loaded by `hie-plugin-api:lib`. It resembles the invocation `stack repl hie-plugin-api:lib` which we use to obtain the compilation flags for the component `hie-plugin-api:lib`. When we have those we can compile the component and provide diagnostics.

We can also provide a File, not only directories, as seen with `./app/MainHie.hs`.
This is the path to the executable `haskell-ide-engine:exe:hie` which needs to be loaded by HIE to actually typecheck the modules.

You need to provide something equivalent for your codebase. The components in your project can be obtained with `stack ide targets`.

**Comment by EdmundsEcho** [comment]
Thank you for your help.  The information was useful.  I used the `stack repl xxx` command to test each entry into the configuration.  It seems to work.  However, in `nvim` I'm getting errors for __all__ of my imports... It seems like I have to  `package.yaml -> hie.yaml`..? 

I installed `hie` using the default script; this uses the latest supported ghc version.  That seems to be `8.8.2` based on what I can see in the list of hie-xxx links in my `~/.local/bin` directory.

However, I get these warning messages when installing `hie`: 
```
# stack (for hie-8.8.2)
Stack has not been tested with GHC versions above 8.6, and using 8.8.2, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail
```
Is this something I need to consider when troubleshooting? (my app lts is set to a value that uses the same, `8.8.2` version of ghc.  I could imagine that it's mostly not something to worry about given my use of the default script and what it promises: "using the latest *supported* ghc".

Despite this logic, the "more I can do" is to install `hie` with `8.6.5` and ditto for my app... I'm not getting the warning but still have the same problem.

Here is my updated `hie.yam` where each entry is the output of `stack ide targests`:
```
cradle:
  stack:
    - path: "./app/Main.hs"
      component: "mms:exe:mms-exe"

    - path: "./src"
      component: "mms:lib"

    - path: "./tests/Spec.hs"
      component: "mms:test:mms-test"
```

![Screen Shot 2020-03-26 at 1 16 42 PM](https://user-images.githubusercontent.com/11245417/77676019-194b4f00-6f64-11ea-93b1-98339d1ddda6.png)
