### ISSUE TITLE
hie only loads the full suite of tests when configured without specifying the root file `Spec.hs`

### ISSUE THREAD

**Issue by EdmundsEcho** [haskell/haskell-ide-engine#1775]
In my coc-nvim context, HIE could not create a cradle when working on a file other than the root test file (`Spec.hs` in this case; a file that imports the rest of the test suite).  However, when I removed the file entry in my `hie.yaml` configuration, all worked as expected.

Specifically,

Given the output from `stack ide targets`:
```
app:lib
app:exe:app-exe
app:test:app-test
```

## the configuration before 
... fails when I edit a file other than `./test/Spec.hs` e.g., HIE fails when working on `./test/API/Struct.hs`.

```yaml
cradle:
  stack:
    - path: "./app/Main.hs"
      component: "app:exe:app-exe"

    - path: "./src"
      component: "app:lib"

    - path: "./test/Spec.hs"     <<<<<
      component: "app:test:app-test"
```

## after
HIE now computes as expected working on files such as `./test/API/Struct.hs`

```yaml
cradle:
  stack:
    - path: "./app/Main.hs"
      component: "app:exe:app-exe"

    - path: "./src"
      component: "app:lib"

    - path: "./test"     <<<<<
      component: "app:test:app-test"
```

I suspect I might be "getting away" with something, i.e., there is another way to be more explicit in how to specify the setup in the `hie.yaml` but I could not see how.

I hope this helps clarify the howto or otherwise describe a bug.

\- E
