### ISSUE TITLE
Support for GHC 8.4.1

### ISSUE THREAD

**Issue by razvan-panda** [haskell/haskell-ide-engine#511]
Are there any plans to add support for GHC 8.4.1?

**Comment by Tehnix** [comment]
I think it will take a little bit of time, as there are quite some migrations that the various packages need to do [to support GHC 8.4.1](https://ghc.haskell.org/trac/ghc/wiki/Migration/8.4). The [`Semigroup`/`Monoid`](https://ghc.haskell.org/trac/ghc/wiki/Migration/8.4#SemigroupMonoidsuperclasses) superclasses seems to be one many are hit by.

I just PR'ed one dependency ([deque](https://github.com/Tehnix/deque)), but it seems there's quite the way to go (cryptonite is the next one I ran into).

**Comment by razvan-panda** [comment]
@Tehnix Is there a pushed branch where there is work done on this?

**Comment by Tehnix** [comment]
Not really, I was just quickly toying around with the following `stack.yaml` :)

```yaml
resolver: nightly-2018-04-01
packages:
- .
- hie-plugin-api

- location:
    git: https://gitlab.com/alanz/HaRe.git
    commit: e325975450ce89d790ed3f92de3ef675967d9538
  extra-dep: true

- location:
    git: https://github.com/alanz/ghc-mod.git
    commit: 47e200a728a575f407ee6f9893d9a1e77b1b5325
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    git: https://github.com/tehnix/deque.git
    commit: 19beedd047d806576b524f332c4c2eee5da953f0
  extra-dep: true


extra-deps:
- apply-refact-0.5.0.0
- brittany-0.10.0.0
- cabal-helper-0.8.0.2
- constrained-dynamic-0.1.0.0
- djinn-ghc-0.0.2.3
- ghc-syb-utils-0.2.3.3
- haddock-api-2.19.0.1
- haskell-lsp-0.2.0.1
- sorted-list-0.2.0.0
- syz-0.2.0.0
- yi-rope-0.10
- butcher-1.3.0.0
- czipwith-1.0.0.0
- data-tree-print-0.1.0.0
- djinn-lib-0.0.1.2
- multistate-0.7.1.2

allow-newer: true

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
```
