### ISSUE TITLE
Autoimports mangles yaml file

### ISSUE THREAD

**Issue by meck** [haskell/haskell-ide-engine#846]
When using the action for adding missing imports it mangles the formatting of yaml files and removes any comments:

Original:
```
name:                test
version:             0.1.0.0
github:              "meck/test"
license:             BSD3
author:              "Johan Eklund"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test

tests:
  test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test
```
After auto importing HTTP:
```
library:
  source-dirs: src
tests:
  test-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test
dependencies:
- HTTP
- base >= 4.7 && < 5
name: test
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Johan Eklund
github: meck/test
license: BSD3
executables:
  test-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test
```
